name: MorphShopsPlus
version: 1.0-ALPHA
main: gg.salvos.morphie.MorphShops
author: Morphie
api-version: 1.13
depend: [Vault]
commands:
 ps:
   description: Main command for MorphShops.
   usage: /<command>
   aliases: [ps, pshop, ms, mshop]